import "./globals.css";
import {Outfit} from "next/font/google";
import Provider from "./Provider";
import {
  ClerkProvider,
} from '@clerk/nextjs'
import { Toaster } from 'react-hot-toast';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const Open=Outfit({subsets: ["latin"]});

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={Open.className}
      >
        <Provider>
        {children}
        </Provider>
        <Toaster />
      </body>
    </html>
    </ClerkProvider>

  );
}
